name: Umineko Exe Release

on:
 push:
   tags:
     - '*'

jobs:
  # Windows Build
  windows_build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      # Download the repository
      - uses: actions/checkout@v3

      - name: Run Build Script
      - run: python build.py

      # Publish a release (tagged commits)
      - name: Release (tag)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # only publish tagged commits
        with:
          files: *.zip
          body_path: release-template.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
